// evals/verification/svelte-wired/fixture/src/FeedbackForm.svelte
<script>
  export let onSaved; // prop-origin callback — parent owns the wiring

  let text = '';
  let error = '';

  async function submit() {
    const res = await fetch('/api/feedback', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ text }),
    });
    if (res.status === 422) {
      const body = await res.json();
      error = body.error;
      return;
    }
    error = '';
    text = '';
    onSaved();
  }

  function clearForm() {
    text = '';
    error = '';
  }
</script>

<form on:submit|preventDefault={submit}>
  <label for="note">Your feedback</label>
  <textarea id="note" bind:value={text} maxlength="500" required></textarea>
  {#if error}<p role="alert">{error}</p>{/if}
  <button type="submit">Submit</button>
  <button type="button" on:click={clearForm}>Clear</button>
</form>

<a href="#top">Back to top</a>

// evals/verification/vue-wired/fixture/src/FeedbackForm.vue
<script setup>
import { ref } from 'vue';

const props = defineProps({ onSaved: Function }); // prop-origin callback — parent owns the wiring

const text = ref('');
const error = ref('');

async function submit() {
  const res = await fetch('/api/feedback', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ text: text.value }),
  });
  if (res.status === 422) {
    const body = await res.json();
    error.value = body.error;
    return;
  }
  error.value = '';
  text.value = '';
  props.onSaved();
}

function clearForm() {
  text.value = '';
  error.value = '';
}
</script>

<template>
  <form @submit.prevent="submit">
    <label for="note">Your feedback</label>
    <textarea id="note" v-model="text" maxlength="500" required></textarea>
    <p v-if="error" role="alert">{{ error }}</p>
    <button type="submit">Submit</button>
    <button type="button" @click="clearForm">Clear</button>
  </form>
  <a href="#top">Back to top</a>
</template>
