// evals/verification/vue-wired/fixture/src/App.vue
<script setup>
import { ref } from 'vue';
import FeedbackForm from './FeedbackForm.vue';

const notes = ref([]);

async function loadFeedback() {
  const res = await fetch('/api/feedback');
  notes.value = await res.json();
}

loadFeedback();
</script>

<template>
  <main id="top">
    <h1>Feedback Board</h1>
    <FeedbackForm :onSaved="loadFeedback" />
    <ul aria-live="polite">
      <li v-for="n in notes" :key="n.id">{{ n.text }}</li>
    </ul>
  </main>
</template>

// evals/preflight/svelte-wired/fixture/src/App.svelte
<script>
  import FeedbackForm from './FeedbackForm.svelte';

  let notes = [];

  async function loadFeedback() {
    const res = await fetch('/api/feedback');
    notes = await res.json();
  }

  loadFeedback();
</script>

<main id="top">
  <h1>Feedback Board</h1>
  <FeedbackForm onSaved={loadFeedback} />
  <ul aria-live="polite">
    {#each notes as n (n.id)}
      <li>{n.text}</li>
    {/each}
  </ul>
</main>
